'use client';

import { motion, useReducedMotion } from 'framer-motion';
import { Receipt } from 'lucide-react';

const lineItems = [
  { item: 'Website Development', qty: 1, total: '$2,400.00' },
  { item: 'SEO Optimization', qty: 3, total: '$450.00' },
  { item: 'Hosting (Annual)', qty: 1, total: '$240.00' },
];

export function InvoiceMockup() {
  const reduce = useReducedMotion();
  const init = (delay = 0) =>
    reduce ? {} : { initial: { opacity: 0, y: 6 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.4, delay } };

  return (
    <div className="mx-auto w-full max-w-sm overflow-hidden rounded-2xl border border-border bg-surface-2">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-border bg-surface px-7 py-4">
        <div className="flex items-center gap-2">
          <Receipt size={18} strokeWidth={1.5} className="text-primary" />
          <span className="font-display text-base font-bold text-foreground">Invoice</span>
        </div>
        <span className="font-mono text-[11px] text-foreground/60">INV-2026-0847</span>
      </div>

      {/* Meta */}
      <motion.div {...init(0.1)} className="flex gap-6 px-7 py-3.5">
        <MetaField label="Date" value="Apr 7, 2026" mono />
        <MetaField label="Bill To" value="John Richardson" />
        <MetaField label="Due" value="May 7, 2026" mono />
      </motion.div>

      <div className="mx-7 h-px bg-border" />

      {/* Table */}
      <div className="px-7">
        <div className="grid grid-cols-[1fr_36px_72px] items-center gap-2 py-2 font-mono text-[9px] font-semibold tracking-widest text-foreground/40">
          <span>ITEM</span>
          <span className="text-center">QTY</span>
          <span className="text-right">TOTAL</span>
        </div>
        <div className="h-px bg-border" />

        {lineItems.map((row, i) => (
          <motion.div key={row.item} {...init(0.2 + i * 0.08)}>
            {i > 0 && <div className="h-px bg-surface" />}
            <div className="grid grid-cols-[1fr_36px_72px] items-center gap-2 py-2.5 text-xs">
              <span className="text-foreground">{row.item}</span>
              <span className="text-center font-mono text-foreground/60">{row.qty}</span>
              <span className="text-right font-mono text-foreground">{row.total}</span>
            </div>
          </motion.div>
        ))}

        <div className="h-px bg-border" />

        {/* Totals */}
        <motion.div {...init(0.5)} className="flex flex-col items-end gap-1.5 py-3">
          <TotalRow label="Subtotal" value="$3,090.00" />
          <TotalRow label="Tax (10%)" value="$309.00" />
          <div className="my-1 h-px w-40 bg-border" />
          <div className="flex items-center gap-6">
            <span className="text-[13px] font-semibold text-foreground">Total Due</span>
            <motion.span
              initial={reduce ? undefined : { opacity: 0, scale: 1.1 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.5, delay: 0.65, ease: [0.22, 1, 0.36, 1] }}
              className="font-mono text-[15px] font-bold text-primary"
            >
              $3,399.00
            </motion.span>
          </div>
        </motion.div>
      </div>

      {/* Footer */}
      <div className="flex items-center justify-between border-t border-border bg-surface px-7 py-3">
        <span className="text-[10px] text-foreground/40">Payment due within 30 days</span>
        <span className="text-[10px] text-primary/40">Generated by Input2PDF</span>
      </div>
    </div>
  );
}

function MetaField({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-[10px] text-foreground/40">{label}</span>
      <span className={`text-xs ${mono ? 'font-mono' : 'font-medium'} text-foreground`}>{value}</span>
    </div>
  );
}

function TotalRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex gap-6">
      <span className="text-[11px] text-foreground/40">{label}</span>
      <span className="font-mono text-xs text-foreground/60">{value}</span>
    </div>
  );
}
