import { Hexagon } from 'lucide-react';

interface LineItem {
  item: string;
  qty: number;
  price: string;
  total: string;
}

const lineItems: LineItem[] = [
  { item: 'Website Development', qty: 1, price: '$2,400.00', total: '$2,400.00' },
  { item: 'SEO Optimization', qty: 3, price: '$150.00', total: '$450.00' },
  { item: 'Hosting (Annual)', qty: 1, price: '$240.00', total: '$240.00' },
];

/* ─── Invoice preview mockup — mirrors designs/Solutions.pen ─── */
export function InvoicePreview() {
  return (
    <div className="mx-auto w-full max-w-xl overflow-hidden rounded-2xl border border-border bg-surface">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-border bg-surface-2 px-7 py-5">
        <div className="flex items-center gap-2">
          <Hexagon size={20} className="text-primary" strokeWidth={1.75} />
          <span className="font-display text-base font-bold text-foreground">Acme Corp</span>
        </div>
        <span className="rounded-md bg-primary/15 px-3 py-1 font-mono text-[10px] font-semibold tracking-wider text-primary">
          INVOICE
        </span>
      </div>

      {/* Meta row */}
      <div className="flex justify-between px-7 py-4">
        <div className="flex flex-col gap-1">
          <span className="text-[11px] text-foreground/45">Invoice #</span>
          <span className="font-mono text-[13px] text-foreground">INV-2024-0847</span>
        </div>
        <div className="flex flex-col gap-1">
          <span className="text-[11px] text-foreground/45">Date</span>
          <span className="font-mono text-[13px] text-foreground">Apr 05, 2026</span>
        </div>
        <div className="flex flex-col gap-1">
          <span className="text-[11px] text-foreground/45">Bill To</span>
          <span className="text-[13px] font-medium text-foreground">John Richardson</span>
        </div>
      </div>

      <div className="h-px bg-border" />

      {/* Table header */}
      <div className="grid grid-cols-[1fr_48px_80px_80px] items-center gap-3 px-7 py-2.5 text-[11px] font-semibold text-foreground/45">
        <span>Item</span>
        <span className="text-center">Qty</span>
        <span className="text-right">Price</span>
        <span className="text-right">Total</span>
      </div>

      {/* Rows */}
      {lineItems.map((row, i) => (
        <div key={row.item}>
          <div
            className={`h-px ${i === 0 ? 'bg-border' : 'bg-surface-2'}`}
          />
          <div className="grid grid-cols-[1fr_48px_80px_80px] items-center gap-3 px-7 py-2.5 text-[13px]">
            <span className="text-foreground">{row.item}</span>
            <span className="text-center font-mono text-foreground/55">{row.qty}</span>
            <span className="text-right font-mono text-foreground/55">{row.price}</span>
            <span className="text-right font-mono text-foreground">{row.total}</span>
          </div>
        </div>
      ))}

      <div className="h-px bg-border" />

      {/* Totals */}
      <div className="flex flex-col items-end gap-2 px-7 py-4">
        <div className="flex gap-6">
          <span className="text-[12px] text-foreground/45">Subtotal</span>
          <span className="font-mono text-[13px] text-foreground/55">$3,090.00</span>
        </div>
        <div className="flex gap-6">
          <span className="text-[12px] text-foreground/45">Tax (10%)</span>
          <span className="font-mono text-[13px] text-foreground/55">$309.00</span>
        </div>
        <div className="my-1 h-px w-48 bg-border" />
        <div className="flex items-center gap-6">
          <span className="text-sm font-semibold text-foreground">Total Due</span>
          <span className="font-mono text-base font-bold text-primary">$3,399.00</span>
        </div>
      </div>

      {/* Footer */}
      <div className="flex items-center justify-between border-t border-border bg-surface-2 px-7 py-3 text-[11px]">
        <span className="text-foreground/45">Payment due within 30 days</span>
        <span className="text-primary/50">Generated by Input2PDF</span>
      </div>
    </div>
  );
}
