/**
 * Case studies dataset (CSE-01).
 *
 * Default stance: anonymized. Named variants require Sarmad's confirmation of client
 * permission per CSE-06 (Badge Bridge outreach in FND-09). To swap an entry to named,
 * flip `anonymized` to false and replace `clientName` + add `clientUrl`.
 *
 * Quality gate (CSE-05): every entry must have metrics.length >= 3 and screenshots.length >= 1
 * and heroImage.src non-empty. TypeScript enforces the first two via the interface; the third
 * is a runtime smoke test covered by tests/case-studies-config.test.ts (Plan 03-15 wave 4).
 *
 * Voice: defer to `docs/input2pdf/input2pdf-description.md` and `.planning/brand-voice.md`.
 * Copy here passes the CMP-04 banned-phrase lint.
 *
 * Asset paths: /case-studies/{slug}/{hero|screenshot-N}.png -- image files produced in Plan 03-09.
 */
import type { CaseStudy } from '@/types/case-study';

export const caseStudies: CaseStudy[] = [
  // 1. Badge Bridge -- flagship, ANONYMIZED BY DEFAULT per CSE-06.
  //    If FND-09 outreach resolves positive before Phase 3 wave 3 merges, flip to named:
  //      anonymized: false,
  //      clientName: 'Badge Bridge',
  //      clientUrl: 'https://meritbadgecourses.com',
  //    and swap screenshots to real (non-mockup) variants.
  {
    slug: 'badge-bridge',
    clientName: 'Scouting badge management platform',
    anonymized: true,
    industry: 'Education · Scouting',
    solutionSlug: 'portals',
    summary:
      'A multi-role portal for badge programs — instructors, admins, and parents each get what they need.',
    problemStatement:
      'The organization ran badge programs for thousands of scouts across dozens of instructors. Every certificate was generated by hand: one spreadsheet per cohort, one document template per badge type, manual delivery by email. Instructors lost hours per cohort; parents chased certificates after the fact.',
    approachSummary:
      'We built a portal where instructors enter completions once and the system handles issuance end-to-end. Badge types live as structured templates. Completions feed a generation pipeline that produces branded PDFs, logs every issuance, and delivers to parents directly. Admins see the full history by scout, instructor, or badge. No more spreadsheets, no more manual PDFs.',
    outcome:
      'Instructors finish cohorts in minutes instead of hours. Parents receive certificates the moment a badge is marked complete. Admins get a searchable history across the entire program.',
    metrics: [
      { label: 'Badge types supported', value: '40+' },
      { label: 'Delivery time', value: 'from days to seconds' },
      { label: 'Instructor time per cohort', value: 'from hours to minutes' },
    ],
    screenshots: [
      {
        src: '/case-studies/badge-bridge/screenshot-1.png',
        alt: 'Instructor dashboard showing cohort overview and recent badge issuances.',
        width: 1200,
        height: 800,
      },
      {
        src: '/case-studies/badge-bridge/screenshot-2.png',
        alt: 'Generated badge certificate with scout name, badge type, and issue date.',
        width: 1200,
        height: 800,
      },
    ],
    heroImage: {
      src: '/case-studies/badge-bridge/hero.png',
      alt: 'Scouting badge management portal — instructor dashboard view.',
      width: 1600,
      height: 900,
    },
    technologies: ['Next.js', 'PostgreSQL', 'Resend', 'pdf-lib'],
    timeline: '6 weeks',
  },

  // 2. Som-Bank -- ANONYMIZED, sensitive client, mockups only per CSE-07.
  {
    slug: 'som-bank',
    clientName: 'Enterprise banking onboarding platform',
    anonymized: true,
    industry: 'Financial services',
    solutionSlug: 'portals',
    summary:
      'An onboarding system that turns regulated intake data into branded, audit-ready onboarding packets.',
    problemStatement:
      'A banking team onboarded new accounts through a mix of paper forms, scanned PDFs, and ad-hoc spreadsheets. Regulated fields had to appear in specific packet layouts per account tier. Every packet was assembled manually and reviewed twice before signature.',
    approachSummary: `We built an intake surface where operators capture the regulated fields once, structured against the bank's own compliance schema. The system composes a tier-specific packet — cover letter, account terms, disclosures, signature blocks — and logs each generation with a timestamp and operator ID. Output ships as a single signature-ready PDF.`,
    outcome:
      'Packet assembly moved from a manual multi-hour process to a single structured entry. Compliance review now validates the schema rather than re-reading every page.',
    metrics: [
      { label: 'Packet assembly time', value: 'from hours to minutes' },
      { label: 'Tier-specific packet layouts', value: '8' },
      { label: 'Manual review steps replaced', value: '12+' },
    ],
    screenshots: [
      {
        src: '/case-studies/som-bank/screenshot-1.png',
        alt: 'Onboarding intake form with structured regulated fields and tier selector.',
        width: 1200,
        height: 800,
      },
      {
        src: '/case-studies/som-bank/screenshot-2.png',
        alt: 'Generated onboarding packet cover page with branded header and account tier label.',
        width: 1200,
        height: 800,
      },
    ],
    heroImage: {
      src: '/case-studies/som-bank/hero.png',
      alt: 'Enterprise banking onboarding platform — system visualization.',
      width: 1600,
      height: 900,
    },
    technologies: ['Next.js', 'Node', 'pdf-lib', 'PostgreSQL'],
    timeline: '8 weeks',
  },

  // 3. Golfer Certificate -- ANONYMIZED per CSE-08 pick #1 (Sports academy achievement certificates).
  //    Bulk generation category.
  {
    slug: 'golfer-cert',
    clientName: 'Sports academy achievement certificates',
    anonymized: true,
    industry: 'Sports · Training academy',
    solutionSlug: 'certificates',
    summary:
      'A bulk certificate pipeline for a sports academy issuing achievement credentials at cohort scale.',
    problemStatement:
      'An academy ran monthly tournaments and end-of-season cohorts. Each event produced dozens of named certificates with tournament type, placement, and coach signature. The admin assembled every certificate by hand from a shared template and mailed scanned copies.',
    approachSummary:
      'We built a bulk-generation flow that takes a roster (CSV or direct entry) and produces one signed certificate per row — correct placement, correct event name, correct date. Output bundles as a ZIP plus individual emails to each recipient. The admin reviews a preview grid before the system commits the send.',
    outcome: `Cohort issuance moved from a day of copy-paste to a single upload. Certificates arrive in recipients' inboxes within minutes of a tournament closing.`,
    metrics: [
      { label: 'Certificates per cohort', value: '50+' },
      { label: 'Issuance time', value: 'from a day to under an hour' },
      { label: 'Template variants supported', value: '6' },
    ],
    screenshots: [
      {
        src: '/case-studies/golfer-cert/screenshot-1.png',
        alt: 'Roster upload screen with tournament metadata and preview grid.',
        width: 1200,
        height: 800,
      },
      {
        src: '/case-studies/golfer-cert/screenshot-2.png',
        alt: 'Generated achievement certificate with recipient name, placement, and signature block — DEMO watermark visible.',
        width: 1200,
        height: 800,
      },
    ],
    heroImage: {
      src: '/case-studies/golfer-cert/hero.png',
      alt: 'Sports academy achievement certificate system — interface overview.',
      width: 1600,
      height: 900,
    },
    technologies: ['Node', 'pdf-lib', 'Resend'],
    timeline: '2 weeks',
  },

  // 4. Pet Puppy Form -- ANONYMIZED per CSE-08 pick #2 (Veterinary intake-to-certificate flow).
  //    Form -> document category.
  {
    slug: 'pet-puppy-form',
    clientName: 'Veterinary intake-to-certificate flow',
    anonymized: true,
    industry: 'Veterinary · Small-animal practice',
    solutionSlug: 'forms',
    summary:
      'An intake form that produces a branded health-record document the moment a practice completes a visit.',
    problemStatement:
      'A small-animal practice collected new-patient details on paper, re-typed them into the practice system, and issued a branded health record by re-keying the same fields into a template document. Every visit meant the same data entered three times.',
    approachSummary: `We replaced the paper intake with a structured web form. On submission, the system produces the practice's branded health-record document with the intake data merged in — ownership details, species, breed, health history, vaccination status. The document delivers to the owner by email and stores in the practice's record system in one pass.`,
    outcome:
      'Data entry dropped from three rounds to one. The branded health record reaches owners within seconds of the visit closing out.',
    metrics: [
      { label: 'Data-entry rounds', value: 'from 3 to 1' },
      { label: 'Intake fields captured', value: '24' },
      { label: 'Document delivery', value: 'from next day to seconds' },
    ],
    screenshots: [
      {
        src: '/case-studies/pet-puppy-form/screenshot-1.png',
        alt: 'Veterinary intake form with structured fields for owner, patient, and visit details.',
        width: 1200,
        height: 800,
      },
      {
        src: '/case-studies/pet-puppy-form/screenshot-2.png',
        alt: 'Generated branded health-record document with intake data merged — DEMO watermark visible.',
        width: 1200,
        height: 800,
      },
    ],
    heroImage: {
      src: '/case-studies/pet-puppy-form/hero.png',
      alt: 'Veterinary intake-to-certificate flow — system visualization.',
      width: 1600,
      height: 900,
    },
    technologies: ['Next.js', 'pdf-lib', 'Resend'],
    timeline: '2 weeks',
  },

  // 5. Agreement Description Form -- ANONYMIZED per CSE-08 pick #3 (Service agreement automation).
  //    Structured input -> legal-style output. DOUBLES as Contracts & eSign proof point per CSE-12.
  //    solutionSlug must be 'contracts' -- relies on Plan 03-03 widening SolutionSlug.
  {
    slug: 'agreement-description',
    clientName: 'Service agreement automation',
    anonymized: true,
    industry: 'Professional services · Agency',
    solutionSlug: 'contracts',
    summary:
      'An intake-to-agreement pipeline that turns a structured brief into a client-ready service agreement.',
    problemStatement:
      'An agency drafted service agreements by copying a master template, replacing fields by hand, and reformatting clauses per engagement. Every agreement took half a day and every engagement introduced small inconsistencies the legal review had to catch.',
    approachSummary: `We built a structured intake that captures the engagement's specifics — scope, deliverables, fees, milestones, jurisdiction, conditional clauses. The system composes the agreement using the agency's own clause library and produces a signature-ready PDF. Optional extension: route to the agency's preferred eSign platform for asynchronous approvals.`,
    outcome:
      'Agreement drafting moved from a half-day of copy-paste to a structured entry and one generate step. Legal review validates the inputs once — the output is consistent by construction.',
    metrics: [
      { label: 'Drafting time per agreement', value: 'from half a day to minutes' },
      { label: 'Clause variants in the library', value: '30+' },
      { label: 'Conditional fields supported', value: '18' },
    ],
    screenshots: [
      {
        src: '/case-studies/agreement-description/screenshot-1.png',
        alt: 'Structured intake form with engagement scope, deliverables, and conditional clause toggles.',
        width: 1200,
        height: 800,
      },
      {
        src: '/case-studies/agreement-description/screenshot-2.png',
        alt: 'Generated service agreement with merged fields and selected clauses — DEMO watermark visible.',
        width: 1200,
        height: 800,
      },
    ],
    heroImage: {
      src: '/case-studies/agreement-description/hero.png',
      alt: 'Service agreement automation — interface overview.',
      width: 1600,
      height: 900,
    },
    technologies: ['Next.js', 'pdf-lib', 'Resend'],
    timeline: '3 weeks',
  },
];

/** Look up a case study by URL slug. Returns undefined if no match (caller should notFound()). */
export function getCaseStudyBySlug(slug: string): CaseStudy | undefined {
  return caseStudies.find((s) => s.slug === slug);
}
